datasources:
  default:
    dialect: POSTGRES
    driverClassName: org.postgresql.Driver
    password: ""
    url: jdbc:postgresql:postgres
    username: postgres

flyway:
  datasources:
    default:
      locations: classpath:db/migration

micronaut:
  application:
    name: domain-persistence-modeling
